exports.productData = [
  {
    name: "Taza pikachu",
    price: 10.99,
    description: "Taza de pikachu",
    rating: 4.5,
    image:
      "https://i.pinimg.com/736x/f4/c3/c9/f4c3c9c1d7ff61ede40a7914a729a6e3.jpg",
    total_sales: 100,
    category: ["Categoría 1", "Categoría 2"],
    is_deleted: false,
  },
  {
    name: "Taza javascript",
    price: 19.99,
    description: "Taza programadora , viene sin chatGPT incluido",
    rating: 3.8,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREfSPTiHVcbVvzQ4iUHp-R0rJziDbwaMtConyVROrZ0gSH2UVExOQvdXniW4NFfneyxM8&usqp=CAU",
    total_sales: 50,
    category: ["Programacion"],
    is_deleted: false,
  },
  {
    name: "Reloj inteligente",
    price: 149.99,
    description: "Reloj inteligente con monitor de actividad",
    rating: 4.7,
    image:
      "https://imagenes.compufull.com/thumb/im_0_0_0_700x700_17454_1/SMART_WATCH_FOXBOX_PROTON_NEGRO20220817131049.jpg",
    total_sales: 95,
    category: ["Tecnología", "Accesorios"],
    is_deleted: false,
  },
  {
    name: "Llavero de saint seiya",
    price: 8.99,
    description: "Llavero de personaje de una serie de anime",
    rating: 4.3,
    image:
      "https://d3ugyf2ht6aenh.cloudfront.net/stores/940/762/products/whatsapp-image-2021-07-01-at-2-40-11-pm1-008bb813e4c89b780116251685290736-640-0.jpeg",
    total_sales: 70,
    category: ["Coleccionables", "Anime"],
    is_deleted: false,
  },
  {
    name: "Gafas de realidad virtual",
    price: 59.99,
    description: "Gafas de realidad virtual para experiencias inmersivas",
    rating: 4.5,
    image:
      "https://www.inovamusicnet.com/wp-content/uploads/2022/11/71URNvzoWqL.AC_SL600_.jpg",
    total_sales: 110,
    category: ["Tecnología", "Gaming"],
    is_deleted: false,
  },
  {
    name: "Camiseta de crash bandicoot",
    price: 19.99,
    description: "Camiseta con diseño de un videojuego popular",
    rating: 4.6,
    image: "https://m.media-amazon.com/images/I/71Bhjn56tcL._AC_UY1100_.jpg",
    total_sales: 80,
    category: ["Ropa", "Gaming"],
    is_deleted: false,
  },
  {
    name: "Carcasa de iron man",
    price: 14.99,
    description: "Carcasa protectora con diseño de personajes de cómic",
    rating: 4.4,
    image:
      "https://img.joomcdn.net/26ddf53c54b8e5676933002e58bef2a6d638e0c3_original.jpeg",
    total_sales: 65,
    category: ["Accesorios", "Tecnología"],
    is_deleted: false,
  },
  {
    name: "Póster de devil may cry",
    price: 9.99,
    description: "Póster con arte de un videojuego popular",
    rating: 4.2,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdj_lQcIvsJz9d0KfuPD6gUUDR8w6L7mXoBA&usqp=CAU",
    total_sales: 55,
    category: ["Decoración", "Gaming"],
    is_deleted: false,
  },
  {
    name: "Figura de wolverine",
    price: 24.99,
    description: "Figura coleccionable de un personaje de cómic",
    rating: 4.8,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIcYZcagKYn6m_86pWK0k_9RGu5N_FNPT8BA&usqp=CAU",
    total_sales: 95,
    category: ["Coleccionables", "Cómic"],
    is_deleted: false,
  },
  {
    name: "Cronicas marcianas",
    price: 12.99,
    description: "Libro de ciencia ficción best-seller",
    rating: 4.5,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOWf-6lT-xNX1cQCH-wqDAbDQsLLDtXRVRNQ&usqp=CAU",
    total_sales: 75,
    category: ["Libros", "Ciencia Ficción"],
    is_deleted: false,
  },
  {
    name: "Puzzle de jumanji",
    price: 19.99,
    description: "Puzzle con ilustración de una película clásica",
    rating: 4.3,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtoGYKqdXaNR-3J9lW6C-pagKtguZzAs4k4GbDhyh5eul2pR0faDKdzfovCKPnBVe9wJc&usqp=CAU",
    total_sales: 60,
    category: ["Juegos", "Cine"],
    is_deleted: false,
  },
  {
    name: "Teclado mecánico red dragon deimos",
    price: 89.99,
    description: "Teclado mecánico retroiluminado para gaming",
    rating: 4.3,
    image:
      "https://www.innovartech.com.ar/storage/2022/03/TECLADO-REDRAGON-DEIMOS.jpg",
    total_sales: 200,
    category: ["Gaming", "Accesorios"],
    is_deleted: false,
  },
  {
    name: "Mouse gamer pulsefire dart negro",
    price: 49.99,
    description: "Mouse ergonómico para juegos de alta precisión",
    rating: 4.5,
    image: "https://image.coolblue.nl/transparent/500x500/products/1914850",
    total_sales: 150,
    category: ["Gaming", "Accesorios"],
    is_deleted: false,
  },
  {
    name: "Auriculares inalámbricos",
    price: 79.99,
    description: "Auriculares inalámbricos con cancelación de ruido",
    rating: 4.8,
    image:
      "https://topesdegama.com/app/uploads-topesdegama.com/2022/02/auriculares-diadema-cancelacio%CC%81n-de-ruido.jpg",
    total_sales: 180,
    category: ["Audio", "Accesorios"],
    is_deleted: false,
  },
  {
    name: "Figura coleccionable god of war",
    price: 29.99,
    description: "Figura de acción coleccionable de un personaje de videojuego",
    rating: 4.6,
    image:
      "https://images-na.ssl-images-amazon.com/images/I/51fXJOGXffL._AC_UL600_SR600,600_.jpg",
    total_sales: 120,
    category: ["Coleccionables", "Gaming"],
    is_deleted: false,
  },
  {
    name: "Camiseta de deadpool",
    price: 19.99,
    description: "Camiseta con el logo de tu superhéroe favorito",
    rating: 4.2,
    image:
      "https://tintografica.com.ar/wp-content/uploads/2021/05/deadpool_negra_rh-600x600.jpg",
    total_sales: 90,
    category: ["Ropa", "Geek"],
    is_deleted: false,
  },
  {
    name: "Taza de café gamer",
    price: 12.99,
    description: "Taza de café con diseño inspirado en videojuegos",
    rating: 4.7,
    image:
      "https://m.media-amazon.com/images/I/51k+YJGNCHL._AC_UF894,1000_QL80_.jpg",
    total_sales: 75,
    category: ["Accesorios", "Cocina"],
    is_deleted: false,
  },
  {
    name: "Poster de volver al futuro",
    price: 9.99,
    description: "Poster de una película clásica de ciencia ficción",
    rating: 4.4,
    image:
      "https://static.wikia.nocookie.net/doblaje/images/0/08/Volver_al_Futuro_Poster.jpg/revision/latest?cb=20201122071805&path-prefix=es",
    total_sales: 60,
    category: ["Decoración", "Cine"],
    is_deleted: false,
  },
  {
    name: "Monopoly",
    price: 34.99,
    description: "Juego de mesa de estrategia para toda la familia",
    rating: 4.9,
    image:
      " https://cdn.idealo.com/folder/Product/5842/9/5842906/s11_produktbild_max/hasbro-monopoly-classic-c1009.jpg",
    total_sales: 110,
    category: ["Juegos de Mesa", "Estrategia"],
    is_deleted: false,
  },
  {
    name: "Lámpara LED",
    price: 24.99,
    description: "Lámpara LED con forma de ícono de videojuego",
    rating: 4.6,
    image:
      "https://www.librephonia.com/26696-medium_default/lampara-de-led-paladone-super-mario-bros-modelo-seta.jpg",
    total_sales: 85,
    category: ["Decoración", "Gaming"],
    is_deleted: false,
  },
];
